apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
    tier: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: client
    tier: web