apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmserver-deployment
  labels:
    app: llmserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmserver
      tier: web
  template:
    metadata:
      labels:
        app: llmserver
        tier: web
    spec:
      containers:
      - name: llmserver
        image: <your deployed ACR name>.azurecr.io/multi-arch:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: 300m
            memory: 8000Mi
          limits:
            cpu: 5000m
            memory: 64000Mi