apiVersion: v1
kind: Service
metadata:
  name: llmserver-service
  labels:
    app: llmserver
    tier: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: llmserver
    tier: web